#api for creating a user account

###

POST  http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "username":"java",
    "email":"java@gmail.com",
    "password":"Password@123"
}



#Api for getting token
###

POST  http://127.0.0.1:8000/api/token/ 
Content-Type: application/json

{
    "username":"django",
    "password":"Password@123"
}

# api for updating user profile

###

PUT http://127.0.0.1:8000/api/profile/
Content-Type: application/json
Authorization: Token 60d5470b2e83788cd2122c2338311f3f1172d2c6

{
    "adress":"address line 1",
    "bio":"djboss",
    "phone":"986563673"
    
}


# api for fetching user profile detail
###

GET http://127.0.0.1:8000/api/profile/
Authorization: Token 60d5470b2e83788cd2122c2338311f3f1172d2c6

#api for getting user detail

###

GET http://127.0.0.1:8000/api/user/
Authorization: Token 60d5470b2e83788cd2122c2338311f3f1172d2c6


#======= Posts=====

# Api for adding a new post

###

POST http://127.0.0.1:8000/api/posts/
Content-Type: application/json
Authorization: Token 60d5470b2e83788cd2122c2338311f3f1172d2c6

{
    "caption":"good morning"

}

###
# api call for listing all posts
GET http://127.0.0.1:8000/api/posts/
Authorization: Token 60d5470b2e83788cd2122c2338311f3f1172d2c6

###
# api cal for fetching specific post details

GET http://127.0.0.1:8000/api/posts/1/
Authorization: Token 60d5470b2e83788cd2122c2338311f3f1172d2c6

